# Generated by Django 3.1.6 on 2021-04-06 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hizmetler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizmetAdi', models.CharField(max_length=50, verbose_name='Hizmet Adı')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='Kisiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('gorev', models.CharField(max_length=50, verbose_name='Gorev')),
                ('telefon', models.PositiveIntegerField(verbose_name='Telefon')),
                ('mail', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('linkedin', models.CharField(max_length=50, verbose_name='LinkedIn')),
                ('whatsapp', models.CharField(max_length=50, verbose_name='Whatsapp')),
                ('instagram', models.CharField(max_length=50, verbose_name='Instagram')),
                ('memleket', models.CharField(max_length=50, verbose_name='LinkedIn')),
                ('dogumTarihi', models.DateField(verbose_name='Doğum Tarihi')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='SaglikKuruluslari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurulusAdi', models.CharField(max_length=50, verbose_name='Başlık')),
                ('kurulusTuru', models.CharField(choices=[('Diş Polikiniği', 'Diş Polikiniği'), ('Özel Hastane', 'Özel Hastane'), ('Kamu Hastanesi', 'Kamu Hastanesi'), ('Estetik Hekimler', 'Estetik Hekimler'), ('IFV', 'IFV')], max_length=20, verbose_name='Kuruluş Türü')),
                ('durum', models.CharField(choices=[('Potansiyel', 'Potansiyel'), ('Yeni', 'Yeni'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Not Working', 'Not Working')], max_length=20, verbose_name='Durum')),
                ('sehir', models.CharField(max_length=50, verbose_name='Şehir')),
                ('ilce', models.CharField(max_length=50, verbose_name='İlçe')),
                ('mahalle', models.CharField(max_length=50, verbose_name='Mahalle')),
                ('sokak', models.CharField(max_length=50, verbose_name='Sokak')),
                ('cadde', models.CharField(max_length=50, verbose_name='Cadde')),
                ('kapıNo', models.PositiveIntegerField(verbose_name='Kapı No')),
                ('tamAdres', models.CharField(max_length=150, verbose_name='Tam Adres')),
                ('postaKodu', models.PositiveIntegerField(verbose_name='Posta Kodu')),
                ('enlem', models.FloatField(max_length=50, verbose_name='Enlem')),
                ('boylam', models.FloatField(max_length=50, verbose_name='Boylam')),
                ('telefon', models.PositiveIntegerField(verbose_name='Telefon')),
                ('fax', models.PositiveIntegerField(verbose_name='Fax')),
                ('website', models.CharField(max_length=50, verbose_name='Website')),
                ('mail', models.EmailField(max_length=50, verbose_name='Mail')),
                ('doktorSayisi', models.PositiveIntegerField(verbose_name='Doktor Sayısı')),
                ('kurulusNotu', models.CharField(max_length=1000, null=True, verbose_name='Yorumunuz.. (En fazla 1000 karakter)')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ekleyen')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='SaglikKisiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('kisiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kisiler', to='base.kisiler')),
                ('saglikID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaglikKisiler', to='base.saglikkuruluslari')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='SaglikHizmetler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('hizmetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.hizmetler')),
                ('kurulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaglikHizmetleri', to='base.saglikkuruluslari')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.AddField(
            model_name='hizmetler',
            name='SaglikHizmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Hizmet', to='base.saglikkuruluslari'),
        ),
    ]
