# Generated by Django 3.1.6 on 2021-04-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notTur', models.CharField(choices=[('İstek', 'İstek'), ('Şikayet', 'Şikayet'), ('Öneri', 'Öneri')], max_length=20, verbose_name='Not Türü')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='Personeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ad')),
                ('soyad', models.CharField(max_length=50, verbose_name='Soyad')),
                ('mail', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('telefon', models.PositiveIntegerField(verbose_name='Telefon')),
                ('sifre', models.CharField(max_length=15, verbose_name='Parola')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='Seviyeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seviyeAdi', models.CharField(max_length=50, verbose_name='Seviye Adı')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='Uzmanliklar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzmanlikAdi', models.CharField(max_length=50, verbose_name='Tedavi Adı')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.AlterField(
            model_name='hizmetler',
            name='SaglikHizmet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='HizmetlerSaglikHizmet', to='base.saglikkuruluslari'),
        ),
        migrations.AlterField(
            model_name='saglikhizmetler',
            name='kurulus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaglikHizmetlerKurulus', to='base.saglikkuruluslari'),
        ),
        migrations.AlterField(
            model_name='saglikkisiler',
            name='kisiID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaglikKisilerKisiID', to='base.kisiler'),
        ),
        migrations.AlterField(
            model_name='saglikkisiler',
            name='saglikID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaglikKisilerSaglikID', to='base.saglikkuruluslari'),
        ),
        migrations.CreateModel(
            name='Tedaviler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tedaviAdi', models.CharField(max_length=50, verbose_name='Tedavi Adı')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('uzmanlikID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TedavilerUzmanlikID', to='base.uzmanliklar')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='SaglikTedaviler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('saglikID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaglikTedavilerSaglikID', to='base.saglikkuruluslari')),
                ('tedaviID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaglikTedavilerTedaviID', to='base.tedaviler')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='SaglikNotlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('notlID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaglikNotlarSaglikID', to='base.notlar')),
                ('sagliklID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SaglikNotlarSaglikID', to='base.saglikkuruluslari')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='PersonelSaglik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('personelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonelSaglikPersonelID', to='base.personeller')),
                ('saglikID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonelSaglikSaglikID', to='base.saglikkuruluslari')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.AddField(
            model_name='personeller',
            name='seviye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PersonellerSeviye', to='base.seviyeler'),
        ),
        migrations.AddField(
            model_name='notlar',
            name='personelID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotlarPersonelID', to='base.personeller'),
        ),
        migrations.CreateModel(
            name='KisiNotlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('kisiID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KisiNotlarKisiID', to='base.kisiler')),
                ('notID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KisiNotlarNotId', to='base.notlar')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
    ]
