# Generated by Django 3.2 on 2021-04-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caddeAdi', models.CharField(max_length=30, verbose_name='Cadde Adı')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilceAdi', models.CharField(max_length=30, verbose_name='İlçe Adı')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='Mahalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahalleAdi', models.CharField(max_length=30, verbose_name='Mahalle Adı')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MahalleIlce', to='base.ilce')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehirAdi', models.CharField(max_length=30, verbose_name='Şehir Adı')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='Sokak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sokakAdi', models.CharField(max_length=30, verbose_name='Sokak Adı')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('mahalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SokakMahalle', to='base.mahalle')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.CreateModel(
            name='KapiNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapiNo', models.CharField(max_length=10, verbose_name='Kapı No')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('cadde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KapıNoCadde', to='base.cadde')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
        migrations.AddField(
            model_name='ilce',
            name='sehir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SehirIlce', to='base.sehir'),
        ),
        migrations.AddField(
            model_name='cadde',
            name='sokak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CaddeSokak', to='base.sokak'),
        ),
    ]
