# Generated by Django 3.1.6 on 2021-04-08 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20210408_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesajlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alıcı', models.CharField(max_length=50, verbose_name='Alıcı')),
                ('okundu', models.BooleanField(verbose_name='Okundu')),
                ('eklenmeTarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'ordering': ['-eklenmeTarihi'],
            },
        ),
    ]
