# Generated by Django 3.2 on 2021-04-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210427_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saglikkuruluslari',
            name='kapiNo',
            field=models.PositiveIntegerField(verbose_name='Kapı No'),
        ),
        migrations.DeleteModel(
            name='KapiNo',
        ),
    ]
