# Generated by Django 3.1.6 on 2021-04-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_mesajlar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesajlar',
            name='mesaj',
            field=models.CharField(default='Mesaj', max_length=250, verbose_name='Mesaj'),
            preserve_default=False,
        ),
    ]
