# Generated by Django 3.1.6 on 2021-04-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_mesajlar_mesaj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajlar',
            name='gonderen',
            field=models.CharField(max_length=50, verbose_name='Gönderen'),
        ),
    ]
