# Generated by Django 3.2 on 2021-04-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20210428_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saglikkuruluslari',
            name='kapiNo',
            field=models.PositiveIntegerField(null=True, verbose_name='Kapı No'),
        ),
    ]
