# Generated by Django 3.1.6 on 2021-04-08 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20210408_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajlar',
            name='gonderen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen'),
        ),
    ]
