# Generated by Django 3.1.6 on 2021-04-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20210408_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajlar',
            name='okundu',
            field=models.BooleanField(default=False, verbose_name='Okundu'),
        ),
    ]
