# Generated by Django 3.1.6 on 2021-04-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210408_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kisiler',
            name='dogumTarihi',
        ),
    ]
