# Generated by Django 3.1.6 on 2021-04-17 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_remove_kisiler_dogumtarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesajlar',
            name='alıcı',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='MesajAlıcı'),
        ),
        migrations.AlterField(
            model_name='mesajlar',
            name='gonderen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MesajGonderıcı', to=settings.AUTH_USER_MODEL),
        ),
    ]
