# Generated by Django 3.2 on 2021-05-11 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0008_remove_kisiler_memleket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=None, null=True, verbose_name='location latitude')),
                ('longitude', models.FloatField(default=None, null=True, verbose_name='location longitude')),
                ('street', models.CharField(max_length=100, verbose_name='street')),
                ('zip_code', models.CharField(max_length=100, verbose_name='zip code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sehir',
            options={'ordering': ['-sehirAdi']},
        ),
        migrations.CreateModel(
            name='UserExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=None, null=True, verbose_name='location latitude')),
                ('longitude', models.FloatField(default=None, null=True, verbose_name='location longitude')),
                ('seviye', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserExtraSeviye', to='base.seviyeler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
