# Generated by Django 3.2 on 2021-05-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20210511_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='seviye',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserExtraSeviye', to='base.seviyeler'),
        ),
    ]
