# Generated by Django 3.1.6 on 2021-04-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210417_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mesajlar',
            old_name='alici',
            new_name='alıcı',
        ),
    ]
