# Generated by Django 3.2 on 2021-05-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userextra_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextra',
            name='userID',
        ),
    ]
