# Generated by Django 3.1.6 on 2021-04-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20210417_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='notlar',
            name='notIcerik',
            field=models.CharField(default='', max_length=1000, verbose_name='Not'),
            preserve_default=False,
        ),
    ]
