# Generated by Django 3.2 on 2021-05-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_userextra_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saglikkuruluslari',
            name='kisiUzaklik',
            field=models.FloatField(max_length=500, null=True, verbose_name='Kişiye Olan Uzaklık'),
        ),
    ]
