# Generated by Django 3.1.6 on 2021-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_notlar_noticerik'),
    ]

    operations = [
        migrations.AddField(
            model_name='personeller',
            name='dogumTarihi',
            field=models.DateField(default='2010-01-01', verbose_name='Doğum Tarihi'),
            preserve_default=False,
        ),
    ]
