# Generated by Django 3.1.6 on 2021-04-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_personeller_dogumtarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personeller',
            name='dogumTarihi',
        ),
    ]
