# Generated by Django 3.1.6 on 2021-04-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_personeller_dogumtarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notlar',
            name='notTur',
            field=models.CharField(choices=[('Istek', 'Istek'), ('Sikayet', 'Sikayet'), ('Oneri', 'Oneri')], max_length=20, verbose_name='Not Türü'),
        ),
        migrations.AlterField(
            model_name='saglikkuruluslari',
            name='kurulusTuru',
            field=models.CharField(choices=[('Dis Polikinigi', 'Dis Polikinigi'), ('Ozel Hastane', 'Ozel Hastane'), ('Kamu Hastanesi', 'Kamu Hastanesi'), ('Estetik Hekimler', 'Estetik Hekimler'), ('IFV', 'IFV')], max_length=20, verbose_name='Kuruluş Türü'),
        ),
    ]
