# Generated by Django 3.1.6 on 2021-04-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20210417_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='cadde',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='doktorSayisi',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='ilce',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='kapıNo',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='kurulusNotu',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='mahalle',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='postaKodu',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='sehir',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='sokak',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='tamAdres',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='telefon',
        ),
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='website',
        ),
    ]
