# Generated by Django 3.1.6 on 2021-04-19 13:30

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20210419_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='saglikkuruluslari',
            name='position',
            field=geoposition.fields.GeopositionField(default=(1, 1), max_length=42),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saglikkuruluslari',
            name='kurulusAdi',
            field=models.CharField(max_length=50, verbose_name='Kuruluş Adı'),
        ),
    ]
