# Generated by Django 3.1.6 on 2021-04-19 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20210419_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saglikkuruluslari',
            name='position',
        ),
    ]
